version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      parcel:
        patterns:
          - "@parcel/*"
          - "parcel"
